#task_name: pubchem_1000
#task_name: pubchem_1000_trick
#task_name: pubchem_250
#task_name: pubchem_250_trick
task_name: pubchem_downstream
#task_name: cliff_data
#batch_size: 256                     # batch size
batch_size: 128                     # batch size
seed: 9
epochs: 100                     # total number of epochs

# pretrain是否采用对抗训练
#pretrain_mode: ad
pretrain_mode: cl

# pretrain的loss是否加入官能团
#pretrain_task: fg
pretrain_task: cl

root: /archive/bioinformatics/Zhou_lab/shared/jjin/SAGE/pretrain_data/
#root: /archive/bioinformatics/Zhou_lab/shared/jjin/SAGE/
is_pretrain: True

save_ckpt: 1
save_model: best_valid
checkpoint: False
#checkpoint: /mnt/8t/qjb/workspace/SCAGE2.0/pretrain_result/model_5.pth
#checkpoint: /mnt/8t/qjb/workspace/SCAGE2.0/pretrain_result/model_5.pth

DP: False
#DP: True
DDP: True
reg_lambda: 1

loss:
  type: NTXentLoss
  param:
    temperature: 0.1
    use_cosine_similarity: True


optim:
  type: adam
  init_lr: 0.0001
  weight_decay: '0'

lr_scheduler:
  type: cos
  warm_up_epoch: 5
  start_lr: 0.00001


model:
  use_sms: True
  # transformer layer
  num_encoder_layers: 4
  hidden_dim: 128
  ffn_hidden_dim: 128
  num_attn_heads: 4
  emb_dropout: 0.4
  dropout: 0.4
  attn_dropout: 0.4
  dist_bar: [ 1, 2, 3 ]
  encoder_normalize_before: True
  apply_graphormer_init: True
  activation_fn: GELU
  n_trans_layers_to_freeze: 0

  use_super_node: True
  graph_pooling: afps
  afps_k: 10

  # 是否使用额外特征
  node_level_modules:
    - degree
  attn_level_modules:
    - geometry
  attn_mask_modules: None

  # PE
  num_in_degree: 512
  num_out_degree: 512
  eig_pos_dim: 3
  svd_pos_dim: 3

  # AT
  num_spatial: 512  # 最短路径的数目
  num_edges: 1536
  num_edge_dis: 128
  edge_type: multi_hop
  multi_hop_max_dist: 5
  num_hop_bias: 3   # 2/3/4

  # GNN
  use_gnn_layers: True
  gnn_insert_pos: before
  num_gnn_layers: 2
  residual: True
  JK: last
  gnn_type: gin
  gnn_dropout: 0.1

  # collator
  max_node: 512
  spatial_pos_max: 20
